### ISSUE TITLE
Design: 투표 종료 컴포넌트 위치와 상태값 관리

### ISSUE THREAD

**Issue by mun-jihye** [Step3-kakao-tech-campus/Team11_FE#124]
## Description
1. 프로토타입에선 투표 종료 버튼 위치가 오른쪽인데 그렇게 하면 모달 내부에선 스타일이 깨져서 왼쪽 상단에 위치 시켰습니다. 혹시 이상할까요?
2. endButton에서 버튼을 누르면 active를 complete로 바꿉니다. 하지만 해당 상태가 voteHead.jsx 파일에도 반영이 되서 투표중이라는 문구가 최종 투표 명수로 바뀌어야 하는데 이 부분 처리를 어떻게 해야할 지 모르겠습니다. active를 전역 변수로 둬야할까요? 그렇다면 recoil을 사용해야하나 ..?

**Comment by ketru44** [comment]
1. 오른쪽 위에 종료 버튼이 있는 게 자연스러울 것 같긴 합니다.. 투표 제목의 위치와 y축 차이가 있더라도(다른 줄에 있더라도) 오른쪽에 두는 게 좋을 것 같아요!!

**Comment by dle234** [comment]
1. 너무 왼쪽에 쏠린느낌이라 오른쪽이 좋을것같긴 해요. 잘 안되면 일단 저렇게 두고 추후에 수정해도 될 것 같습니다.
2.  클릭 시 서버에 요청 보내면 디테일에 보내는 데이터 값이 변경되어서 votehead 도 바뀌지 않을까요..?  그리고 투표 종료 하기 전 투표를 종료하시겠습니까? 라는 알람창같은거 띄워도 좋을것같아요!
3. 메인버튼 레이아웃 바꿔서 디테일 페이지 프롭스값 (what, username...)한번 수정해줘야할것같아요!

**Comment by mun-jihye** [comment]
넵!!
일단 그럼 투표 종료 버튼을 오른쪽에 구현하는 방식으로 가볼께요!
알림창도 추가하겠습니다!
