### ISSUE TITLE
Q. CSS 수정사항

### ISSUE THREAD

**Issue by dle234** [Step3-kakao-tech-campus/Team11_FE#136]
페이지별 스타일 수정사항이 있는것같아서(물론 알고 있겠지만 정리할겸 적어둘게요..!)
* 로그인, 회원가입
   - [x] 1200px 로 화면 늘렸을때 '계정이 없으신가요?' 와 로그인 라벨 겹침
   - [x] 회원가입도 마찬가지로 화면 늘렸을때 글자가 위로 올라감
   - [x] 헤더 고정안됨(이거는 하면 좋겠지만 꼭 필요하진 않은듯)
   - [x] 중복검사버튼 화면 늘렸을때 깨짐(absolute 말고 input 컴포넌트에 넣는 식으로 하는게 더 좋을 것 같아요!)

* 모달창
  - [x] 뒷 배경 움직임(멘토링, 코드리뷰 받을 것)
  - [x] 모달창을 높이를 고정한다음에 컨테이너를 스크롤 하는게 아니라 그 안 부분만 스크롤 할 수 있게 하면 좋을 것 같아요(그리고 위에 padding 없애는게 나을것같습니다..!)

* 마이페이지
  - [x] 내가 참여한 투표나 내가 한 질문 같은 경우 글자 색, 글자 크기, 높이, 선 굵기, border-radius 등을 피그마에 나와있는 것 처럼 맞춰주세요!
  - [x] 이미지 넣을때 Img 컴포넌트 사용하면 크기에 맞게 알아서 잘라줘서 안늘어나요..! 그거 사용하시면 좋을 것 같습니다.
  - [x] container 넣어주기(1000px 이상 늘렸을때 뒷배경도 같이 늘어나요!)

메인페이지, 업로드 페이지도 추가 수정하고 싶은 사항 있으면 알려주세요!!

**Comment by mun-jihye** [comment]
중복 검사 버튼 input안에 넣으면 사라지는데 이거 어떻게 구현하면 좋을까요??
(일요일에 이야기하기 !! )

**Comment by mun-jihye** [comment]
모달 창 안에 스크롤을 넣으라는게 댓글이 많아질 경우를 예상해서 넣으라는걸까요 ??
